### ISSUE TITLE
[Question] How to run multiple tunnels simultaneously?

### ISSUE THREAD

**Issue by aborovsky** [bubenshchykov/ngrok#101]
I've tried the topic in 2 ways.

First one.

```
ngrok.connect({addr: 22, proto: 'tcp'}, (err, url) => {...})
ngrok.connect({addr: 80, proto: 'http'}, (err, url) => {...})
```
tunnel for port 22 fails to start, but 80 works.

Second one.

`ngrok.yml` created with content:
```
tunnels:
  nodered:
    proto: http
    addr: 1880
    region: 'eu'
  ssh:
    proto: tcp
    addr: 22
    region: 'eu'
```

start ngrok:
```
    ngrok.connect({region: 'eu', configPath: 'ngrok.yml'}, listenerFunc);
```
and `listenerFunc` doesn't work, it's never called.

Ho to properly run few tunnels with ngrok simulataneously?
